src/Entity/SearchRequest.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use App\Validator\Constraints as AppAssert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SearchRequestRepository")
 * @AppAssert\StayDateRange(startDate="getCheckIn", endDate="getCheckOut")
 */
class SearchRequest
{
    const STATUS_NEW = 0;
    const STATUS_COMPLETE = 1;
    const STATUS_OLD = 2;
    const STATUS_ERROR = 3;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue()
     *
     * @var int
     */
    private $id;

    /**
     * @Assert\NotBlank()
     * @ORM\ManyToOne(targetEntity="City")
     * @var City
     */
    private $city;

    /**
     * @Assert\Date()
     * @Assert\NotBlank()
     * @ORM\Column(type="date")
     * @var \DateTime
     */
    private $checkIn;

    /**
     * @Assert\Date()
     * @Assert\NotBlank()
     * @ORM\Column(type="date")
     * @var \DateTime
     */
    private $checkOut;

    /**
     * @ORM\Column(type="integer")
     * @var int
     */
    private $adults = 1;

    /**
     * @ORM\Column(type="datetime")
     * @var \DateTime
     */
    private $createdAt;

    /**
     * @ORM\Column(type="integer")
     * @var int
     */
    private $status = self::STATUS_NEW;

    public function __construct()
    {
        $this->createdAt = new \DateTime();
        $this->checkIn = new \DateTime('+ 2 day');
        $this->checkOut = new \DateTime('+ 9 day');
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return City
     */
    public function getCity(): ?City
    {
        return $this->city;
    }

    /**
     * @param City $city
     * @return SearchRequest
     */
    public function setCity(City $city): SearchRequest
    {
        $this->city = $city;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getCheckIn(): ?\DateTime
    {
        return $this->checkIn;
    }

    /**
     * @param \DateTime $checkIn
     * @return SearchRequest
     */
    public function setCheckIn(\DateTime $checkIn): SearchRequest
    {
        $this->checkIn = $checkIn;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getCheckOut(): ?\DateTime
    {
        return $this->checkOut;
    }

    /**
     * @param \DateTime $checkOut
     * @return SearchRequest
     */
    public function setCheckOut(\DateTime $checkOut): SearchRequest
    {
        $this->checkOut = $checkOut;
        return $this;
    }

    /**
     * @return int
     */
    public function getAdults(): ?int
    {
        return $this->adults;
    }

    /**
     * @param int $adults
     * @return SearchRequest
     */
    public function setAdults(int $adults): SearchRequest
    {
        $this->adults = $adults;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt(): \DateTime
    {
        return $this->createdAt;
    }

    /**
     * @return int
     */
    public function getStatus(): int
    {
        return $this->status;
    }

    /**
     * @param int $status
     * @return SearchRequest
     */
    public function setStatus(int $status): SearchRequest
    {
        $this->status = $status;
        return $this;
    }

    /**
     * @return bool
     */
    public function isCompleted(): bool
    {
        return in_array($this->status, [self::STATUS_COMPLETE, self::STATUS_OLD]);
    }

    /**
     * @return bool
     */
    public function isError(): bool
    {
        return $this->status == self::STATUS_ERROR;
    }

    /**
     * @return bool
     */
    public function isNew(): bool
    {
        return $this->status == self::STATUS_NEW;
    }
}

src/Controller/TestController.php
<?php

namespace App\Controller;

use App\Entity\SearchRequest;
use App\Entity\SearchResult;
use App\Form\SearchRequestType;
use App\Repository\SearchResultRepository;
use App\Service\HotelSearch;;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * Class TestController
 * @package App\Controller
 */
class TestController extends Controller
{
    /**
     * @Route("/test", name="test")
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $form = $this->createForm(SearchRequestType::class, new SearchRequest());
        $form->handleRequest($request);
        $hasSearchError = false;
        if ($form->isSubmitted() && $form->isValid()) {
            /** @var SearchRequest $searchRequest */
            $searchRequest = $form->getData();
            $searchService = $this->get(HotelSearch::class);
            if ($searchService->search($searchRequest)) {
                return $this->redirectToRoute('test_results', ['searchRequest' => $searchRequest->getId(), 'page' => 1]);
            } else {
                $hasSearchError = true;
            }
        }
        return $this->render(
            'Test/index.html.twig',
            [
                'form' => $form->createView(),
                'hasSearchError' => $hasSearchError
            ]
        );
    }

    /**
     * @Route("/test/results/{searchRequest}/{page}", name="test_results", requirements={"searchRequest"="\d+", "page"="\d+"}, defaults={"page"=1})
     * @param SearchRequest $searchRequest
     * @param int $page
     * @return Response
     */
    public function results(SearchRequest $searchRequest, int $page = 1)
    {
        $templateVars = array(
            'form' => $this
                ->createForm(
                    SearchRequestType::class,
                    $searchRequest,
                    ['action' => $this->generateUrl('test')]
                )
                ->createView(),
            'request' => $searchRequest
        );
        if ($searchRequest->isCompleted()) {
            /** @var SearchResultRepository $repository */
            $repository = $this->getDoctrine()->getRepository(SearchResult::class);
            $query = $repository->createQueryForPagination($searchRequest);
            $paginator = $this->get('knp_paginator');
            $templateVars['pagination'] = $paginator->paginate($query, $page, 50);
        }

        return $this->render('Test/results.html.twig', $templateVars);
    }
}

templates/Test/index.html.twig
{% extends 'base.html.twig' %}

{% block test_active%} active{% endblock %}

{% block body %}
    <div class="jumbotron">
        <h1>Поиск отелей</h1>
        {{ form(form) }}
    </div>
{% endblock %}

templates/Test/results.html.twig
{% extends 'base.html.twig' %}

{% block test_active%} active{% endblock %}

{% block body %}
    <div class="jumbotron hidden">
        <h1>Поиск отелей</h1>
        {{ form(form) }}
    </div>
    <div class="row">
        <div class="col-lg-12"></div>
    </div>
    {% if request.error %}
        <div class="row">
            <div class="col-lg-12 alert alert-danger">
                Поиск завершился ошибкой, попробуйте повторить или изменить параметры
            </div>
        </div>
    {% elseif request.new %}
        <div class="row">
            <div class="col-lg-12 alert alert-warning">
                Поиск ещё не был завершен. Повторите попытку позже.
            </div>
        </div>
    {% else %}
        {# total items count #}
        <div class="row">
            <div class="col-lg-12 text-muted">
                Всего предложений: {{ pagination.getTotalItemCount }}
            </div>
        </div>
        <div>
            {{ knp_pagination_render(pagination) }}
        </div>
        {# table body #}
        {% for item in pagination.items %}
            <div class="row">
                <div class="col-lg-1">{{ loop.index + pagination.getItemNumberPerPage * (pagination.page - 1) }}</div>
                <div class="col-lg-6">
                    <span class="text-capitalize">{{ item.hotel.name }}</span>
                    <span class="text-primary">{{ item.roomName }}</span>
                    <span class="text-muted">({{ item.meal.name }})</span>
                </div>
                <div class="col-lg-2">{{ item.price.amount }} {{ item.price.currency }}</div>
            </div>
        {% endfor %}
        {# display navigation #}
        <div>
            {{ knp_pagination_render(pagination) }}
        </div>
    {% endif %}
{% endblock %}